//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Rest_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public Nullable<int> CartID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Car { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> QuantityInHand { get; set; }
        public string Image { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
